### ISSUE TITLE
Restrict secure-only (https) cookies

### ISSUE THREAD

**Issue by dylex** [tekul/broch#32]
A recent audit flagged the session bsid cookies as missing the secure flag.  Looks like it's just commented out in
https://github.com/tekul/broch/blob/master/Broch/Server/Session.hs#L126
Is there an easy way to enable this without re-implementing `defaultLoadSession`?

**Comment by tekul** [comment]
Aren't you compiling the code anyway, so you can just enable the flag if you want?

Alternatively, since the header value is just a `ByteString`, you can modify that directly and add the `Secure` attribute. Or if you are running behind a proxy you can probably rewrite the cookie there. For example, in nginx you can use `proxy_cookie_path`.
