### ISSUE TITLE
Please make a hackage release

### ISSUE THREAD

**Issue by jappeace** [tekul/broch#33]
At supercede we've made a [yesod integration](https://hackage.haskell.org/package/yesod-auth-oidc) for this library.
However it currently doesn't build out of the box because this library was never uploaded to hackage.
Please upload this software to hackage!

**Comment by tekul** [comment]
Sorry, but I don't consider this code in its current state to be something I would want to release as a package, nor do I have the time or interest to maintain such a release (I'm not doing much Haskell these days). You are of course free to use the code as you see fit, based on the license. As far as I can see, your library is an OpenID client integration so should not directly require a server side integration in order to function.
